stages:
  - verify

runner_verify:
  stage: verify

  image: node:22-alpine

  tags:
    - docker
    - taskflow
    - aws

  script:
    - echo "GitLab Runner is working"
    - echo "Runner description: $CI_RUNNER_DESCRIPTION"
    - echo "Project: $CI_PROJECT_PATH"
    - echo "Branch: $CI_COMMIT_BRANCH"
    - node --version
    - npm --version
    - cat /etc/os-release
