stages:
  - verify

runner_verify:
  stage: verify

  image: docker:27-cli

  tags:
    - docker
    - taskflow
    - aws

  variables:
    DOCKER_HOST: unix:///var/run/docker.sock

  script:
    - echo "Checking Docker access..."
    - docker version
    - docker info
    - docker ps